### PR TITLE
Add Client::getLastRequest

### LINKED ISSUE #16: Add getLastRequest and getLastResponse/Exception methods
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

#### Actual Behavior

These methods does not exist, one need to fetch all of the aformentioned objects and get the one from the top manually.

#### Expected Behavior

Since in many cases we only test one HTTP call at a time, it should probably be easier to do that.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #16
| Documentation   | https://github.com/php-http/documentation/pull/213
| License         | MIT

#### What's in this PR?

Add getters for last response, exception and request.

#### Why?

Because @sagikazarmark asked for it. :wink: 

#### Example Usage

See the doc PR

#### Checklist

- [x] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
- [x] Documentation pull request created (if not simply a bugfix)

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
> or is there a good use case for them?

Well, not for me personally. Maybe @sagikazarmark cans explain it?

**Comment by sagikazarmark** [comment]
> Because @sagikazarmark asked for it. 😉 

I would like to....... 😝 

Jokes aside: I can't recall the exact use case for those two (maybe I could have written a better issue description).

I can think of a case when you configure the MockClient outside of your test case (with some common input) and you can't access that input directly. In those cases these methods could be useful, not sure how valid this case is.

**Comment by Soullivaneuh** [comment]
> I can think of a case when you configure the MockClient outside of your test case

Maybe as a Symfony service for example? https://github.com/php-http/HttplugBundle/issues/212

**Comment by Soullivaneuh** [comment]
Conflicts resolved.

**Comment by sagikazarmark** [comment]
Hm, maybe. Can't decide whether it's good or bad, but I can't see any issues with having them. @dbu ?

**Comment by dbu** [comment]
i find them confusing because i don't see legit use cases for it. they can be added when somebody has an actual use case for them imho.

but i can life with them if you insist on having them ;-)

**Comment by sagikazarmark** [comment]
> i like the getLastRequest method

Do you still think this is useful? Or should we just drop this (BTW sorry @Soullivaneuh )

**Comment by dbu** [comment]
getlastrequest sounds more useful to me. you can check what the last request that has been sent contained, and make  assertions on it and so on.

**Comment by Soullivaneuh** [comment]
So do you want me to let only `getLastRequest` on this PR?

**Comment by Soullivaneuh** [comment]
I updated this PR.

Well, it looks @Nyholm merge the docs one too quickly, here is a correction: https://github.com/php-http/documentation/pull/216

**Comment by dbu** [comment]
sorry, this went under... @Soullivaneuh would you mind checking if the doc is now correct on this one as its merged?

**Comment by Soullivaneuh** [comment]
@dbu The doc is good according to me. 

Could we have a new release since all the PR are merged? :-)

**Comment by Nyholm** [comment]
I've reviewed the changes. I think it's alright to tag 1.1.0. 

I have not been a part of the latest PRs so I leave it to other maintainer to do the tag.

**Pull request merged**
